### ISSUE TITLE
API email notifications does not work

### ISSUE THREAD

**Issue by syphax-bouazzouni** [lifewatch-eric/ontologies_api#9]
All the notification email sent in the API does not work, including the one to reset the password.  

Digging into the logs, we can see the following error message, `Net::SMTPAuthenticationError - 530 5.5.1 Authentication Required`, which indicates the configurations of the email client are not correct. 

So we need to update the config file in `/srv/ontoportal/ontologies_api/current/config/environments/appliance.rb`, with the correction credentials to the mail server.

then restart, the services `sudo oprestart`

**Comment by gturrisi-lifewatch** [comment]
The credentials in the file `/srv/ontoportal/ontologies_api/current/config/environments/appliance.rb` are correct and they are the same set in `/srv/ontoportal/virtual_appliance/appliance_config/bioportal_web_ui/config/bioportal_config_appliance.rb`

You can try to use the Feedback form `https://ecoportal.lifewatch.eu/feedback` that works well and send correctly the email to the user. So I think the problem is not related to username, password or smtp parameters.

**Comment by syphax-bouazzouni** [comment]
Yes, I have noticed that. But I think it may be that the API domain `https://data.ecoportal.lifewatch.eu/`, is not accepted by the SMTP server?  I'm not really aware of how the SMTP servers work,  can you check that?

In the code it does work for us at Agroportal (but we don't use login authentication)

**Comment by syphax-bouazzouni** [comment]
A temporary solution would be to hide the reset password link, with a message indicating to send an email to support.
@gturrisi-lifewatch can you see if you can disable the authentication?

**Comment by gturrisi-lifewatch** [comment]
I cannot find the possibility to disable authentication in the Zoho account settings

<img width="375" alt="Screenshot 2023-10-26 alle 17 37 28" src="https://github.com/lifewatch-eric/ontologies_api/assets/117273860/f7a480de-f234-49a8-a03a-309f8eb9689c">

**Comment by syphax-bouazzouni** [comment]
fixed in #11
